feat: :hammer: se añade una nueva función para desarrollo del reto uno
AutomatizacionClaro/RetosJava pull request #2
Opened 2023-11-22 23:54 UTC by Ctabares1993

Buen día, se crea PR con la solución del reto uno para su aprobación.

![image](https://github.com/AutomatizacionClaro/RetosJava/assets/142419951/62f76d5b-dabd-4594-86df-b1281edda5c1)

2023-11-23 13:39 UTC, jandres-dev requested changes
Se realizan comentarios, favor revisar.

2023-11-23 13:39 UTC, jandres-dev commented on src/retos/david/SolucionRetoUno.java
> -        // Favor crear una rama y al terminar el reto, lanzar el PR
Eliminar este comentario.

2023-11-23 13:39 UTC, jandres-dev commented on src/retos/david/SolucionRetoUno.java
>      }
Buen día Davincho, la lógica que tienes esta bien porque el programa cumple con el resultado del reto. A modo opcional pero NO es necesario que lo cambies pero esta lógica se puede reducir, ya que para este ejemplo solo se necesitan 3 condiciones:

numero % 3 == 0 ---> múltiplos de 3 "fizz"
numero % 5 == 0 ---> múltiplos de 5 "buzz"
numero % 3 == 0 && numero % 5 == 0 "fizzbuzz"

todo lo demás iría en un else que en este caso sería (numero).

2023-12-04 06:18 UTC, Ctabares1993 commented on src/retos/david/SolucionRetoUno.java
> -        // Favor crear una rama y al terminar el reto, lanzar el PR
Se elimina comentario

2023-12-04 21:29 UTC, IoNakamura approved these changes
Se aprueban PR

2023-12-04 21:30 UTC, merged